server:
  port: 8080
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/homesecure'
    username: 'homesecure'
    password : 'homesecure'
    driver-class-name: 'org.postgresql.Driver'
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
