server:
  port: 8080
  servlet:
    context-path= /api
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/homesecure'
    username: 'homesecure'
    password : 'homesecure'
    driver-class-name: 'org.postgresql.Driver'